spring.application.name=order-service

server.port=8081

#spring.profiles.active=h2
spring.profiles.active=mysql
#spring.profiles.active=postgres

#JPA
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

## Kafka configurations
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
