#H2-DB
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.admin.auto-create=false
#spring.kafka.listener.missing-topics-fatal=false
#
#spring.rabbitmq.listener.simple.auto-startup=false
#spring.rabbitmq.listener.direct.auto-startup=false
#
#spring.autoconfigure.exclude=\
#org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration,\
#org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration